version: '3.8'

services:
  app:
    image: frontend
    build:
      context: ./todo-frontend # The context will pick this directory as the "build context"
      dockerfile: ./Dockerfile # This will simply tell which dockerfile to read
    volumes:
      - ./todo-frontend:/usr/src/app # The path can be relative, so ./ is enough to say "the same location as the docker-compose.yml"
    environment:
        - REACT_APP_BACKEND_URL=http://localhost:8080/api
        - PORT=3000
        - WDS_SOCKET_PORT=0
        - WATCHPACK_POLLING=true
    container_name: frontend
    depends_on:
      - server
  server:
    image: backend
    build:
      context: ./todo-backend
      dockerfile: ./Dockerfile
    volumes:
      - ./todo-backend:/usr/src/app
    ports:
      - "3000:3000"
    environment: 
      - REDIS_URL=redis://redis:6379
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes: 
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./todo-backend/mongo_data:/data/db
  redis:
    image: redis
    ports:
      - 6379:6379
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - ./todo-backend/redis_data:/data
    container_name: redis
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - app
volumes:
  mongo_data: